name: Build Docker Image

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: "Commit SHA or tag (refs/tags/vX.X.X) to build the image from."
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags
          ref: ${{ github.event.inputs.tag || github.ref }} # Checkout the specified tag or branch

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag and version
        run: |
          TAG=${{ github.event.inputs.tag || github.ref }}
          VERSION=${TAG#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/drezzing/drezzing-frontend:latest
            ghcr.io/drezzing/drezzing-frontend:${{ env.VERSION }}
